-- Enums
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

CREATE TYPE "BookingStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED');

CREATE TYPE "CarCategory" AS ENUM (
  'ECONOMY', 'COMPACT', 'MIDSIZE', 'LUXURY', 'SUV', 
  'VAN', 'CLASSIC', 'CONVERTIBLE', 'EXOTIC', 
  'SEDAN', 'SPORT', 'SUPER'
);
